# Generated by Django 5.0 on 2023-12-18 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='Укажите имя')),
                ('text', models.TextField(verbose_name='Введите текст отзыва...')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200, verbose_name='Название роли')),
            ],
        ),
        migrations.CreateModel(
            name='RoleUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200, verbose_name='Название роли')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taskapp.team'),
        ),
        migrations.AlterField(
            model_name='task',
            name='Status',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='taskapp.role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='taskapp.roleuser'),
        ),
    ]
