# Generated by Django 5.0 on 2023-12-18 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_review_role_roleuser_task_team_alter_task_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Description', models.TextField(blank=True)),
                ('Status', models.CharField(default=0, max_length=50)),
                ('Priority', models.IntegerField()),
                ('Start', models.DateTimeField()),
                ('End', models.DateTimeField()),
                ('AssignedUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taskapp.user')),
            ],
        ),
    ]
