# Generated by Django 5.0 on 2023-12-13 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_role_teammember_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200, verbose_name='Название роли')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='Role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='taskapp.roleuser'),
        ),
    ]
